#+TITLE: Emacs configuration
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

This is my personal Emacs configuration file

* Init
** Package repositories
   Setup the default package repositories used by this config
   
   #+BEGIN_SRC emacs-lisp
   (require 'package)
   
   (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
   (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
   (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
   
   (setq package-enable-at-startup nil)
   (package-initialize)
   #+END_SRC

** Disable GUI
   I don't use the toolbar and menu bar at all, so hide them to give more screen real estate to the editor

   #+BEGIN_SRC emacs-lisp
   (when (fboundp 'menu-bar-mode) (menu-bar-mode -1))
   (when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
   (when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))   
   #+END_SRC

** use-package

   This installs the ~use-package~ package, that will make installing and 
   managing packages in this config much cleaner

   #+BEGIN_SRC emacs-lisp
   (unless (package-installed-p 'use-package)
     (package-refresh-contents)
     (package-install 'use-package))
   
   (eval-when-compile
     (require 'use-package))
   #+END_SRC
   
   Now to ensure a package is installed you simply use ~(use-package name-of-the-package :ensure t)~, easy!

** Dashboard
   Uses the ~emacs-dashboard~ package for a pretty start screen featuring recent projects and files

   #+BEGIN_SRC emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook))

  (setq dashboard-startup-banner 'logo)
  (setq dashboard-set-footer nil)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-show-shortcuts nil)

  (setq dashboard-items '((projects  . 5)
                          (recents . 5)
                          (bookmarks . 5)
                          (agenda . 5)
                          (registers . 5)))

   #+END_SRC

* Appearence
** Startup
   Maximize screen, so we get the prettier startup screen but also because we extremely rarley want a screen as small as the default
   #+BEGIN_SRC emacs-lisp
   (toggle-frame-maximized)
   #+END_SRC
   
   Install =all-the-icons=, used by various other plugins
   #+BEGIN_SRC emacs-lisp
   (use-package all-the-icons :ensure t)
   (unless (member "all-the-icons" (font-family-list))
     (all-the-icons-install-fonts t))
   #+END_SRC

** Theme
   For the theme we are using zenburn
   #+BEGIN_SRC emacs-lisp
   (use-package zenburn-theme :ensure t)
   (load-theme 'zenburn t)
   #+END_SRC
   
   Modify the appearance of highlighted text to make it actually readable
   #+BEGIN_SRC emacs-lisp
   (set-face-attribute 'region nil :background "#333" :foreground "#ffffff")
   #+END_SRC

** Modeline 
   [[https://github.com/seagle0128/doom-modeline][doom-modeline]] is "A fancy and fast mode-line inspired by minimalism design"
   
   #+BEGIN_SRC emacs-lisp
   (use-package doom-modeline 
     :ensure t
     :hook (after-init . doom-modeline-mode))
   #+END_SRC

** Dired 
*** Packages
    Install plugins related to dired
    #+BEGIN_SRC emacs-lisp
    (use-package dired-subtree :ensure t
      :after dired)
    (use-package all-the-icons-dired :ensure t)
    (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
    #+END_SRC

*** General
    Use emulated ls by default, so it is consistent between different OSes
    #+BEGIN_SRC emacs-lisp
    (setq ls-lisp-use-insert-directory-program nil)
    #+END_SRC

    Hide details by default
    #+BEGIN_SRC emacs-lisp
    (add-hook 'dired-mode-hook
      (lambda ()
        (dired-hide-details-mode) ; Hide details by default
        ))
    #+END_SRC

*** Keybindings
    #+BEGIN_SRC emacs-lisp
      (bind-key "<tab>" #'dired-subtree-toggle dired-mode-map)
      (bind-key "<backtab>" #'dired-subtree-cycle dired-mode-map)
    #+END_SRC

* General
** Helm
  [[https://github.com/emacs-helm/helm][Helm]] is the emacs incremental completion and selection narrowing framework
  In other words it's a very good fuzzy finder that can be used pretty much everywhere in emacs!
  
*** Packages
   Install the packages

   #+BEGIN_SRC emacs-lisp
   (use-package helm :ensure t) ; Main helm
   #+END_SRC

*** Keybindings
   Helm
   #+BEGIN_SRC emacs-lisp
   (global-set-key (kbd "M-x") 'helm-M-x)
   #+END_SRC

*** General
   Always open helm in the bottom of the frame
   #+BEGIN_SRC emacs-lisp
   (setq helm-default-display-buffer-functions '(display-buffer-in-side-window))
   #+END_SRC

** Keybindings
   Unbind keys that interefers with the shortcut keys for swedish characters in OSX
   #+BEGIN_SRC emacs-lisp
   (global-unset-key (kbd "M-a"))
   (global-unset-key (kbd "M-u"))
   #+END_SRC

* Text manipulation
** Evil
  [[https://github.com/emacs-evil/evil][Evil]] is The extensible vi layer for Emacs
  
*** Packages
   Install the package

   #+BEGIN_SRC emacs-lisp
   (use-package evil :ensure t)
   (require 'evil)
   #+END_SRC

*** Configuration
   Use Evil mode as default

   #+BEGIN_SRC emacs-lisp
   (evil-mode t)
   #+END_SRC

*** Keybindings
    #+BEGIN_SRC emacs-lisp
    (unbind-key "C-p" evil-normal-state-map) ; Used by Projectile
    (define-key evil-normal-state-map (kbd "C-u") 'evil-scroll-up) 
    #+END_SRC

** evil-easymotion
   Easymotion for Evil mode
   
*** Packages
   #+BEGIN_SRC emacs-lisp
   (use-package evil-easymotion :ensure t)
   #+END_SRC
   
*** Keybindings
   #+BEGIN_SRC emacs-lisp
   (evilem-default-keybindings "SPC")
   #+END_SRC

* File/Project management
** Projectile
   [[https://github.com/bbatsov/projectile][Projectile]] is a project interaction library for Emacs.
   
*** Packages
   Install package and enable Projectile
   #+BEGIN_SRC emacs-lisp
   (use-package projectile :ensure t)   
   (projectile-mode +1)
   #+END_SRC
   
   Install helm integration
   #+BEGIN_SRC emacs-lisp
   (use-package helm-projectile :ensure t)   
   #+END_SRC

*** Keybindings
   Set keybindings for Projectile
   #+BEGIN_SRC emacs-lisp
   (define-key projectile-mode-map (kbd "C-p") 'projectile-command-map)
   (define-key projectile-mode-map (kbd "C-p f") 'helm-projectile-find-file)
   (define-key projectile-mode-map (kbd "C-p p") 'helm-projectile-switch-project)
   #+END_SRC

*** Settings
   With this setting, once you have selected your project, the top-level directory of the project is immediately opened for you in a dired buffer.
   #+BEGIN_SRC emacs-lisp
   (setq projectile-switch-project-action #'projectile-dired)
   #+END_SRC

* Org
** Appearence
    [[https://github.com/sabof/org-bullets][org-bullets]] adds pretty bullets to org mode

    #+BEGIN_SRC emacs-lisp
    (use-package org-bullets :ensure t)
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
    #+END_SRC

** Export
*** Html
   Htmlize allows for html export of org documents

   #+BEGIN_SRC emacs-lisp
   (use-package htmlize :ensure t)
   #+END_SRC

   
   
